describe('smeproduct - 2nd page', ()  => {
 
    beforeEach(() => {
        cy.visit('https://ms.yoors.com.au/ergo-sme/#/about?id=95117&token=b1a731d5-20e2-407a-b745-b305e44ce0b6')
        })
        

        it("Proceed button check" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
        })

        it('Verify the location Selector name', () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#locationSelector').should('have.text','Location Selector')

        })

        it('Verify the Location Selector - Location Table-color', () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#locationSelector').should('have.text','Location Selector')
            //cy.get('#locationsubHeadding0').should('have.text','Location 1 : Postal Code - Unit No ')
            cy.get('.location_active').should('have.css','background-color','rgb(220, 53, 69)')
        })

          

        it("Basic insurance coverage text check" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#basicInsuranceCoverage1').should('have.text',' Basic Insurance Coverage ')  // 2nd page -Basic Insurance Coverages
        })

        it("Verify the view additional lable" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#propertyAllRiskBtn').should('have.text','View Additional Extensions') // view additional lable
        })

        it("Verify the 'view additional lable' button" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#propertyAllRiskBtn').click()
        })

        it("Verify the content of view additional popup-PAR" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#propertyAllRiskBtn').click()    
            cy.get('#PAR_h5_').should('have.text','SPECIFIC EXTENSIONS TO THIS SECTION')   //View Additional Extensions
            cy.get('#PAR_p_1').should('have.text','1. Cost of Recompiling Records and Claims Preparation')
            cy.get('#PAR_p_2').should('have.text','2. Deterioration of Stock')
            cy.get('#PAR_p_3').should('have.text','3. Full Theft Extension')
            cy.get('#PAR_p_4').should('have.text','4. Goods in Transit')
            cy.get('#PAR_p_5').should('have.text','5. Reinstatement of Fire Extinguishing Appliances')
            cy.get('#PAR_p_6').should('have.text','6. Locks & Keys')
            cy.get('#PAR_p_7').should('have.text','7. Plans and Documents')
            cy.get('#PAR_p_8').should('have.text','8. Plate Glass')
            cy.get('#PAR_i_').click({force: true})
        })
        it("Verify the content of view additional popup-PAR" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#propertyAllRiskToolTip1').trigger('mouseover')
        })

        it("Verify the postal code- label" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode').should('have.text','Postal Code :') // postal code lable
        })
        it("Verify the postal code" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399')
        })

        it("Verify Unit number-label" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode').should('have.text','Postal Code :') // postal code lable
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399')
            cy.get('#UnitNo').should('have.text','Unit No :') //unit no lable

        })
        it("Verify Unit number" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#viewActivities1Btn').click()
            cy.get('#ViewActivities_i_').click()
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399')
            cy.get('#unitNo0').clear({force: true})
            cy.get('#unitNo0').type('34F5')

        })

        it("Verify Content" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399') 
            cy.get('#unitNo0').clear({force: true})
            cy.get('#unitNo0').type('34F5')
            cy.get('#locationConSi0').clear()
            cy.get('#locationConSi0').type('1000000') 

        })

        it("Verify Stock" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click() 
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399') 
            cy.get('#unitNo0').clear({force: true})
            cy.get('#unitNo0').type('34F5')
            cy.get('#locationConSi0').clear({force: true})
            cy.get('#locationConSi0').type('1000000') 
            cy.get('#locationStkSi0').clear({force: true})
            cy.get('#locationStkSi0').type('5000')
            cy.wait(2000)

        })

        it("Verify PA optional coverage" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399')
            cy.get('#unitNo0').clear({force: true})
            cy.get('#unitNo0').type('34F5')
            cy.get('#locationConSi0').clear({force: true})
            cy.get('#locationConSi0').type('1000000') 
            cy.get('#locationStkSi0').clear({force: true})
            cy.get('#locationStkSi0').type('5000')
            cy.wait(2000)
            cy.get('#selectedPersonaleAccidentSelect0').select('3')   //Personal Accident
            cy.get('#selectPersonaleAccidentValueSelect0').select('1')
            cy.get('#name00').type('Lithinika')   
            cy.get('#occupationInput00').type('QA')
            cy.get('#idType00').select('1')
            cy.get('#nric00').type('S4300010A')
            cy.get('#paNationalityInput00').type('Gabon')
            cy.get('#dateofBirth00').click()
            cy.contains("[title='Select year']", '2007').select('2007')
            cy.contains("[title='Select month']", 'Apr').select('4')
            cy.get("[aria-label='Wednesday, April 25, 2007']").click()  
            cy.get('#paGenderSelected00').select('F')

        })
        it("Verify WICA description" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399')
            cy.get('#unitNo0').clear({force: true})
            cy.get('#unitNo0').type('34F5')
            cy.get('#locationConSi0').clear({force: true})
            cy.get('#locationConSi0').type('1000000') 
            cy.get('#locationStkSi0').clear({force: true})
            cy.get('#locationStkSi0').type('5000')
            cy.wait(2000)
            cy.get('#wica0').select('Y')
            cy.get('#wicsDesc2').should('have.text','Employees Information :')
            cy.get('#wicsDesc3').should('have.text',' "Estimated annual Earnings" means an amount, not less than the past annual Earnings of the Insured, declared by the Insured to be an estimate of the total earnings to be paid by the Insured (as well as by other employers and known to the insured) during the 12 months starting on the commencement date of the policy. ')
            cy.get('#wicsDesc4').should('have.text',' "Past Annual Earnings" means the total of the monthly earning paid by the insured (as well as by other employers and known to the Insured) during the 12 months immediately before the commencement date of the policy. ')
            cy.get('#wicsDesc5').should('have.text',' The types of remuneration that constitute "Earnings" are set out in section 2 of the Work Injury Compensation Act 2019. ')
            cy.get('#wicsWarningDesc1').should('have.text','Warning')
            cy.get('#wicsWarningDesc2').should('have.text',' If the Insured misrepresents the number of employees, job category or the Estimated Annual Earnings: ')
            cy.get('#wicsWarningDesc3').should('have.text'," The amount of the Company's indemnity to the Insured for a claim will be reduced proportionately by the extent of under-insurance. The Insured will bear its proportionate share of the liability and the Company may recover this amount from the Insured under clause 13,or ")
            cy.get('#wicsWarningDesc4').should('have.text',' The Company may recover from the Insured the amount paid to a claimant which is attributable to any Relevant Injury arising in relation to those non-disclosed or misstated material facts under clause 8(1)(a) ')
            
        })
        it("Verify WICA table" , () => {
            cy.get('#myBusiness').select('3')   
            cy.get('#aboutOccupationDesc').clear()
            cy.get('#aboutOccupationDesc').type('l23')
            cy.get('#viewActivityStatus').select('N')
            cy.get('#fromDate').click()
            cy.contains("[title='Select year']", '2024').select('2024')
            cy.contains("[title='Select month']", 'May').select('5')
            cy.get("[aria-label='Friday, May 31, 2024']").click()
            cy.get('#selectexception').select('Yes')
            cy.get('#acceptProceed').click()
            cy.get('#postalCode0').clear({force: true})
            cy.get('#postalCode0').type('299399')
            cy.get('#unitNo0').clear({force: true})
            cy.get('#unitNo0').type('34F5')
            cy.get('#locationConSi0').clear({force: true})
            cy.get('#locationConSi0').type('1000000') 
            cy.get('#locationStkSi0').clear({force: true})
            cy.get('#locationStkSi0').type('5000')
            cy.wait(2000)
            cy.get('#wica0').select('Y')
            cy.get('#Employees').should('have.text','Employees')
            cy.get('#Headcount').should('have.text','Headcount :')
            cy.wait(2000)
            cy.get('#headcountId00').select('2')
            cy.get('#jobCategory00').select('Outdoor (Non-Manual)')
            cy.get('#wagerollId00').type('10000')
            
            
        })

        

    it("Verify locations - 1-20" , () => {
        cy.get('#myBusiness').select('3')   
        cy.get('#viewActivities1Btn').click()
        cy.get('#ViewActivities_i_').click()
        cy.get('#aboutOccupationDesc').clear()
        cy.get('#aboutOccupationDesc').type('l23')
        cy.get('#viewActivityStatus').select('N')
        cy.get('#fromDate').click()
        cy.contains("[title='Select year']", '2024').select('2024')
        cy.contains("[title='Select month']", 'May').select('5')
        cy.get("[aria-label='Friday, May 31, 2024']").click()
        cy.get('#selectexception').select('Yes')
        cy.get('#acceptProceed').click()
        cy.get('#postalCode0').clear()
        cy.get('#postalCode0').type('299399')
        cy.get('#unitNo0').clear()
        cy.get('#unitNo0').type('34F5')
        cy.get('#locationConSi0').clear()
        cy.get('#locationConSi0').type('1000000') 
        cy.get('#stocks').should('have.text','Stocks :') // stock lable
        cy.get('#locationStkSi0').clear({force: true})
        cy.get('#locationStkSi0').type('5000')
        cy.wait(2000)
        cy.get('#selectedPersonaleAccidentSelect0').select('3')   //Personal Accident
        cy.get('#selectPersonaleAccidentValueSelect0').select('1')
        cy.get('#name00').type('Lithinika')   
        cy.get('#occupationInput00').type('QA')
        cy.get('#idType00').select('1')
        cy.get('#nric00').type('S4300010A')
        cy.get('#paNationalityInput00').type('Gabon')
        cy.get('#dateofBirth00').click()
        cy.contains("[title='Select year']", '2007').select('2007')
        cy.contains("[title='Select month']", 'Apr').select('4')
        cy.get("[aria-label='Wednesday, April 25, 2007']").click()  
        cy.get('#paGenderSelected00').select('F')
        cy.get('#addLocation').click()
        cy.get('#postalCode1').clear()   // location no. 2
        cy.get('#postalCode1').type('299398')
        cy.get('#unitNo1').clear()
        cy.get('#unitNo1').type('1ABC')
        cy.get('#locationConSi1').clear()
        cy.get('#locationConSi1').type('750000')
        cy.wait(2000)
        cy.get('#liability1').select('3')     // Public Liability
        cy.wait(2000)
        cy.get('#selectedFireI1').select('Y')   //Fire and Extraneous Perils on Building
        cy.wait(2000)
        cy.get('#fireBuildingI1').clear()
        cy.get('#fireBuildingI1').type('30000')
        cy.wait(2000)
        cy.get('#fidelityGuarantee1').select('7500')
        cy.get('#perLimitEmployee1').select('2')
        cy.get('#addLocation').click()
        cy.get('#postalCode2').clear()   // location no.3
        cy.get('#postalCode2').type('299398')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi2').clear()
        cy.get('#locationConSi2').type('500000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode3').clear()   // location no.4
        cy.get('#postalCode3').type('569933')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi3').clear()
        cy.get('#locationConSi3').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode4').clear()   // location no.5
        cy.get('#postalCode4').type('189928')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi4').clear()
        cy.get('#locationConSi4').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode5').clear()   // location no.6
        cy.get('#postalCode5').type('189927')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi5').clear()
        cy.get('#locationConSi5').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode6').clear()   // location no.7
        cy.get('#postalCode6').type('189971')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi6').clear()
        cy.get('#locationConSi6').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode7').clear()   // location no.8
        cy.get('#postalCode7').type('189969')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi7').clear()
        cy.get('#locationConSi7').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode8').clear()   // location no.9
        cy.get('#postalCode8').type('189970')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi8').clear()
        cy.get('#locationConSi8').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode9').clear()   // location no.10
        cy.get('#postalCode9').type('520110')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi9').clear()
        cy.get('#locationConSi9').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode10').clear()   // location no.11
        cy.get('#postalCode10').type('050335')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi10').clear()
        cy.get('#locationConSi10').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode11').clear()   // location no.12
        cy.get('#postalCode11').type('247964')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi11').clear()
        cy.get('#locationConSi11').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode12').clear()   // location no.13
        cy.get('#postalCode12').type('546080')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi12').clear()
        cy.get('#locationConSi12').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode13').clear()   // location no.14
        cy.get('#postalCode13').type('308215')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi13').clear()
        cy.get('#locationConSi13').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode14').clear()   // location no.15
        cy.get('#postalCode14').type('238858')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi14').clear()
        cy.get('#locationConSi14').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode15').clear()   // location no.16
        cy.get('#postalCode15').type('571150')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi15').clear()
        cy.get('#locationConSi15').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode16').clear()   // location no.17
        cy.get('#postalCode16').type('570150')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi16').clear()
        cy.get('#locationConSi16').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode17').clear()   // location no.18
        cy.get('#postalCode17').type('521147')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi17').clear()
        cy.get('#locationConSi17').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode18').clear()   // location no.19
        cy.get('#postalCode18').type('520147')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi18').clear()
        cy.get('#locationConSi18').type('1000000')
        cy.wait(2000)
        cy.get('#addLocation').click()
        cy.get('#postalCode19').clear()   // location no.20
        cy.get('#postalCode19').type('310145')
        //cy.get('#unitNo2').clear()
        //cy.get('#unitNo2').type('12#')
        cy.get('#locationConSi19').clear()
        cy.get('#locationConSi19').type('1000000')
        cy.wait(2000)
        cy.get('#nextBtn').click({force: true})

    })

    
        

    


})
    
    